spring:
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  application:
    name: IoTMining-Auth-Service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*" # health,info,metrics,prometheus
      server:
        request:
          autotime:
            enabled:false
      base-path: /actuator
    prometheus:
      enabled: true  # Make sure this is enabled
  metrics:
    export:
      prometheus:
        enabled: true  # Enable Prometheus export
    enable:
      jvm: true  # Ensure JVM metrics are enabled

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true  # Use IP instead of hostname for discovery